<?php

namespace Phossa\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 08:50:06.
 */
class EventManagerTest
    extends \PHPUnit_Framework_TestCase
{

    /**
     * @var EventManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EventManager;
        require_once __DIR__ . '/Listener.php';
        require_once __DIR__ . '/ListenerStatic.php';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Phossa\Event\EventManager::processEvent
     */
    public function testProcessEvent1()
    {
        $l = new Listener();
        $this->object->attachListener($l);

        // event stopped by testY
        $e1 = new Event('evtTest4', $this);
        $e1 = $this->object->processEvent($e1);
        $this->assertArrayHasKey(
            'testX', $e1->getProperties()
        );
        $this->assertArrayHasKey(
            'testY', $e1->getProperties()
        );
        $this->assertArrayNotHasKey(
            'testZ', $e1->getProperties()
        );
    }

    /**
     * @covers Phossa\Event\EventManager::processEvent
     */
    public function testProcessEvent2()
    {
        // test static listener
        $this->object->attachListener('Phossa\\Event\\ListenerStatic');

        // event stopped by testY
        $e1 = new Event('evtTest3', $this);
        $e1 = $this->object->processEvent($e1);
        $this->assertArrayHasKey(
            's_testA', $e1->getProperties()
        );
        $this->assertArrayHasKey(
            's_testB', $e1->getProperties()
        );
    }

    /**
     * @covers Phossa\Event\EventManager::processEvent
     */
    public function testProcessEvent3()
    {
        $l = new Listener();
        $this->object->attachListener($l);

        // normal
        $e1 = new Event('evtTest3', $this);
        $e1 = $this->object->processEvent($e1, function() {
            return true;
        });
        $this->assertArrayHasKey(
            'testA', $e1->getProperties()
        );
        $this->assertArrayHasKey(
            'testB', $e1->getProperties()
        );

        // stopped by callback
        $e2 = new Event('evtTest3', $this);
        $e2 = $this->object->processEvent($e2, function() {
            return false;
        });
        $this->assertArrayHasKey(
            'testA', $e2->getProperties()
        );
        $this->assertArrayNotHasKey(
            'testB', $e2->getProperties()
        );
    }

    /**
     * @covers Phossa\Event\EventManager::attachListener
     */
    public function testAttachListener1()
    {
        // the right object
        $l = new Listener();
        $this->object->attachListener($l);
    }

    /**
     * @covers Phossa\Event\EventManager::attachListener
     * @expectedException Phossa\Event\Exception\InvalidArgumentException
     * @expectedExceptionCode Phossa\Event\Message\Message::INVALID_EVENT_LISTENER
     */
    public function testAttachListener2()
    {
        // the wrong object
        $o = new \stdClass();
        $this->object->attachListener($o);
    }

    /**
     * @covers Phossa\Event\EventManager::attachListener
     */
    public function testAttachListener3()
    {
        // attach static class
        $this->object->attachListener('Phossa\\Event\\ListenerStatic');
    }

    /**
     * @covers Phossa\Event\EventManager::detachListener
     */
    public function testDetachListener1()
    {
        $l = new Listener();
        $this->object->attachListener($l);

        // detach one
        $this->assertTrue($this->object->hasEventQueue('evtTest3'));
        $this->object->detachListener($l, 'evtTest3');
        $this->assertTrue($this->object->hasEventQueue('evtTest3') == false);

        // detach all
        $this->object->detachListener($l);
        $this->assertTrue(0 === count($this->object->getEventNames()));
    }

    /**
     * @covers Phossa\Event\EventManager::detachListener
     * @expectedException Phossa\Event\Exception\InvalidArgumentException
     * @expectedExceptionCode Phossa\Event\Message\Message::INVALID_EVENT_LISTENER
     */
    public function testDetachListener2()
    {
        $l = new \stdClass();
        $this->object->detachListener($l);
    }

    /**
     * @covers Phossa\Event\EventManager::detachListener
     */
    public function testDetachListener3()
    {
        // detach static class
        $class = 'Phossa\\Event\\ListenerStatic';
        $this->object->attachListener($class);
        $this->assertTrue(3 === count($this->object->getEventNames()));
        $this->object->detachListener($class);
        $this->assertTrue(0 === count($this->object->getEventNames()));
    }

    /**
     * @covers Phossa\Event\EventManager::hasEventQueue
     */
    public function testHasEventQueue()
    {
        $l = new Listener();
        $this->object->attachListener($l);

        // check attached event
        $this->assertTrue($this->object->hasEventQueue('evtTest2'));

        $this->assertTrue(false === $this->object->hasEventQueue('evtTestX'));
    }

    /**
     * @covers Phossa\Event\EventManager::getEventQueue
     */
    public function testGetEventQueue()
    {
        $l = new Listener();
        $this->object->attachListener($l);

        // check attached event
        $q = $this->object->getEventQueue('evtTest2');
        foreach ($q as $data) {
            $this->assertTrue(20 === $data['priority']);
            $this->assertTrue([$l, 'testD'] === $data['data']);
        }

        // attach static again
        $this->object->attachListener('Phossa\\Event\\ListenerStatic');
        $q = $this->object->getEventQueue('evtTest2');
        $this->assertTrue(2 === $q->count());
    }

    /**
     * @covers Phossa\Event\EventManager::clearEventQueue
     */
    public function testClearEventQueue()
    {
        $l = new Listener();
        $this->object->attachListener($l);

        $this->assertTrue($this->object->hasEventQueue('evtTest3'));
        $this->object->clearEventQueue('evtTest3');
        $this->assertTrue($this->object->hasEventQueue('evtTest3') == false);
    }

    /**
     * @covers Phossa\Event\EventManager::getEventNames
     */
    public function testGetEventNames()
    {
        $l = new Listener();
        $this->object->attachListener($l);

        // check attached event
        $evts = $this->object->getEventNames();
        $this->assertTrue($evts === array_keys($l->getEventsListening()));
    }

}
