<?php
namespace Phossa\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 08:50:05.
 */
class EventCapableTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EventCapableInterface
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        require_once __DIR__.'/EventCapable.php';
        $this->object = new EventCapable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Event\EventCapable::setEventCapable
     */
    public function testSetEventCapable()
    {
        $this->object->setEventManager(
            new EventManager()
        );
    }

    /**
     * @covers Phossa\Event\EventCapable::triggerEvent
     */
    public function testTriggerEvent()
    {
        $manager = new EventManager();
        require_once __DIR__.'/Listener.php';
        require_once __DIR__.'/ListenerStatic.php';
        $manager->attachListener(new Listener());
        $manager->attachListener('Phossa\\Event\\ListenerStatic');

        $this->object->setEventManager(
            $manager,
            function($e, $c, $p) {
                return new Event($e, $c, $p);
            }
        );

        $e1 = $this->object->triggerEvent('evtTest4');
        $this->assertArrayHasKey('testY', $e1->getProperties());

        $e2 = $this->object->triggerEvent('evtTest2');
        $this->assertArrayHasKey('testD', $e2->getProperties());
        $this->assertArrayHasKey('s_testDD', $e2->getProperties());
    }
}
