<?php
namespace Phossa\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 08:50:05.
 */
class EventAwareStaticTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        require_once __DIR__.'/EventAwareStatic.php';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * set event manager for static class
     *
     * @covers Phossa\Event\EventAwareStatic::setEventManagerStatically
     */
    public function testSetEventManager1()
    {
        EventAwareStatic::setEventManagerStatically(
            new EventManager()
        );
    }

    /**
     * set event manager and event factory for static class
     *
     * @covers Phossa\Event\EventAwareStatic::setEventManagerStatically
     */
    public function testSetEventManager2()
    {
        EventAwareStatic::setEventManagerStatically(
            new EventManager(),
            new Event('prototype')
        );
    }

    /**
     * @covers Phossa\Event\EventAwareStatic::triggerEventStatically
     */
    public function testTriggerEvent()
    {
        $manager = new EventManager();
        require_once __DIR__.'/Listener.php';
        require_once __DIR__.'/ListenerStatic.php';
        $manager->attachListener(new Listener());
        $manager->attachListener('Phossa\\Event\\ListenerStatic');

        EventAwareStatic::setEventManagerStatically($manager);

        $e1 = EventAwareStatic::triggerEventStatically('evtTest4');

        // has 'testY'
        $this->assertArrayHasKey('testY', $e1->getProperties());
        // stopped after 'testY'
        $this->assertArrayNotHasKey('testZ', $e1->getProperties());

        // both object/static listener has 'evtTest2'
        $e2 = EventAwareStatic::triggerEventStatically('evtTest2', ['x' => 'xx']);
        $this->assertArrayHasKey('testD', $e2->getProperties());
        $this->assertArrayHasKey('s_testDD', $e2->getProperties());
        $this->assertArrayHasKey('x', $e2->getProperties());
    }
}
